# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

# if we provide this we need to manage it, It has managed nodegroups
# nodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true
